// <auto-generated />
using System;
using BlazorCrud.Server.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorCrud.Server.EntityFramework.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorCrud.Shared.Domain.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "LEGO"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hot Wheels"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Funko"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marvel"
                        });
                });

            modelBuilder.Entity("BlazorCrud.Shared.Domain.Toy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToyType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Toys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Name = "Star Wars Star Destroyer",
                            ToyType = 4
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 3,
                            Name = "Pop Cyberpunk 2077 - Johnny Silverhand",
                            ToyType = 0
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            Name = "Honda Civic Type S",
                            ToyType = 0
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 4,
                            Name = "Spiderman - The Game (PS5)",
                            ToyType = 2
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 4,
                            Name = "Iron Man Action Figure",
                            ToyType = 0
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 4,
                            Name = "Hulk Action Figure",
                            ToyType = 0
                        });
                });

            modelBuilder.Entity("BlazorCrud.Shared.Domain.Toy", b =>
                {
                    b.HasOne("BlazorCrud.Shared.Domain.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.Navigation("Brand");
                });
#pragma warning restore 612, 618
        }
    }
}
